Chat
SamaritaninS/Itirod pull request #1
Opened 2021-03-24 14:11 UTC by SamaritaninS

2021-03-25 19:25 UTC, gmltA requested changes
https://github.com/saba024/Front-end_labs/

Good start!

2021-04-03 11:29 UTC, SamaritaninS commented
Извините за первый раз, решил сразу еще добавить подгрузку истории как во втором варианте.

2021-04-05 14:46 UTC, gmltA requested changes
Па-першае я не прасіў вас дадаваць такі функцыянал. Але раз вы так вырашылі...
Гісторыя не павінна захоўвацца ў файле.

2021-04-24 15:50 UTC, gmltA approved these changes

2021-10-01 10:40 UTC, closed without merging